# Parte 1 – Filtrado y preprocesamiento

In [54]:
# Importar las librerías necesarias
import pandas as pd
import json

In [55]:
# 2. Cargar la información del archivo large_even.json en una lista
with open('large_eve.json', 'r') as f:
    data = [json.loads(line) for line in f]
print(f"Total de registros: {len(data)}")  # Debería ser 746909

Total de registros: 746909

In [56]:
# 3. Filtrar registros DNS
data_dns = [record for record in data if record.get('event_type') == 'dns']

In [57]:
# 4. Mostrar la nueva cantidad de registros filtrados
print(f"Total de registros DNS: {len(data_dns)}")  # Debería ser 21484

Total de registros DNS: 15749

In [58]:
# 5. Mostrar la información de 2 registros cualesquiera
print(data_dns[0])
print(data_dns[100])

{'timestamp': '2017-07-22T17:33:16.661646-0500', 'flow_id': 1327836194150542, 'pcap_cnt': 22269, 'event_type': 'dns', 'vlan': 110, 'src_ip': '2001:0dbb:0c18:0011:0260:6eff:fe30:0863', 'src_port': 59680, 'dest_ip': '2001:0500:0001:0000:0000:0000:803f:0235', 'dest_port': 53, 'proto': 'UDP', 'dns': {'type': 'query', 'id': 15529, 'rrname': 'api.wunderground.com', 'rrtype': 'A', 'tx_id': 0}}
{'timestamp': '2017-07-22T17:33:27.398815-0500', 'flow_id': 2090016796251365, 'pcap_cnt': 54532, 'event_type': 'dns', 'vlan': 150, 'src_ip': '192.168.207.4', 'src_port': 53, 'dest_ip': '192.168.205.170', 'dest_port': 36690, 'proto': 'UDP', 'dns': {'type': 'answer', 'id': 26728, 'rcode': 'NXDOMAIN', 'rrname': '<root>', 'rrtype': 'SOA', 'ttl': 20864}}

In [59]:
# 6. Normalizar la información y asignarla en un dataframe
df = pd.json_normalize(data_dns)
print(df.shape)  # Debería ser (21484, 163)

(15749, 18)

In [60]:
df

,timestamp,flow_id,pcap_cnt,event_type,vlan,src_ip,src_port,dest_ip,dest_port,proto,dns.type,dns.id,dns.rrname,dns.rrtype,dns.tx_id,dns.rcode,dns.ttl,dns.rdata
0,2017-07-22T17:33:16.661646-0500,1327836194150542,22269,dns,110,2001:0dbb:0c18:0011:0260:6eff:fe30:0863,59680,2001:0500:0001:0000:0000:0000:803f:0235,53,UDP,query,15529,api.wunderground.com,A,0.0,NaN,NaN,NaN
1,2017-07-22T17:33:24.990320-0500,2022925111925872,54352,dns,110,2001:0dbb:0c18:0011:0260:6eff:fe30:0863,38051,2001:0500:0003:0000:0000:0000:0000:0042,53,UDP,query,58278,stork79.dropbox.com,A,0.0,NaN,NaN,NaN
2,2017-07-22T17:33:27.379891-0500,578544790391795,54519,dns,150,192.168.205.170,31393,192.168.207.4,53,UDP,query,54724,hpca-tier2.office.aol.com.ad.aol.aoltw.net,A,0.0,NaN,NaN,NaN
3,2017-07-22T17:33:27.380146-0500,578544790391795,54520,dns,150,192.168.207.4,53,192.168.205.170,31393,UDP,answer,54724,hpca-tier2.office.aol.com.ad.aol.aoltw.net,NaN,NaN,NXDOMAIN,NaN,NaN
4,2017-07-22T17:33:27.380146-0500,578544790391795,54520,dns,150,192.168.207.4,53,192.168.205.170,31393,UDP,answer,54724,<root>,SOA,NaN,NXDOMAIN,20864.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15744,2017-07-22T19:47:03.373435-0500,891876064866556,4441474,dns,120,192.168.207.4,53,192.168.202.172,60654,UDP,answer,33107,en-us.start3.mozilla.com,NaN,NaN,NXDOMAIN,NaN,NaN
15745,2017-07-22T19:47:03.373435-0500,891876064866556,4441474,dns,120,192.168.207.4,53,192.168.202.172,60654,UDP,answer,33107,<root>,SOA,NaN,NXDOMAIN,20864.0,NaN
15746,2017-07-22T19:47:38.146503-0500,2199315651640391,4452917,dns,130,192.168.203.67,50975,192.168.207.4,53,UDP,query,35892,whitecell.localdomain,AAAA,0.0,NaN,NaN,NaN
15747,2017-07-22T19:47:38.146953-0500,2199315651640391,4452918,dns,130,192.168.207.4,53,192.168.203.67,50975,UDP,answer,35892,whitecell.localdomain,NaN,NaN,NXDOMAIN,NaN,NaN
15748,2017-07-22T19:47:38.146953-0500,2199315651640391,4452918,dns,130,192.168.207.4,53,192.168.203.67,50975,UDP,answer,35892,<root>,SOA,NaN,NXDOMAIN,20864.0,NaN

In [61]:
# 7. Filtrar los registros DNS para aquellos registros tipo A
df_a = df[df['dns.rrtype'] == 'A'].copy()
print(df_a.shape)  # Debería ser (2849, 163)
df_a.head()

(2849, 18)

,timestamp,flow_id,pcap_cnt,event_type,vlan,src_ip,src_port,dest_ip,dest_port,proto,dns.type,dns.id,dns.rrname,dns.rrtype,dns.tx_id,dns.rcode,dns.ttl,dns.rdata
0,2017-07-22T17:33:16.661646-0500,1327836194150542,22269,dns,110,2001:0dbb:0c18:0011:0260:6eff:fe30:0863,59680,2001:0500:0001:0000:0000:0000:803f:0235,53,UDP,query,15529,api.wunderground.com,A,0.0,NaN,NaN,NaN
1,2017-07-22T17:33:24.990320-0500,2022925111925872,54352,dns,110,2001:0dbb:0c18:0011:0260:6eff:fe30:0863,38051,2001:0500:0003:0000:0000:0000:0000:0042,53,UDP,query,58278,stork79.dropbox.com,A,0.0,NaN,NaN,NaN
2,2017-07-22T17:33:27.379891-0500,578544790391795,54519,dns,150,192.168.205.170,31393,192.168.207.4,53,UDP,query,54724,hpca-tier2.office.aol.com.ad.aol.aoltw.net,A,0.0,NaN,NaN,NaN
5,2017-07-22T17:33:36.672785-0500,237919524635665,55496,dns,110,2001:0dbb:0c18:0011:0260:6eff:fe30:0863,41663,2001:07fd:0000:0000:0000:0000:0000:0001,53,UDP,query,45082,api.wunderground.com,A,0.0,NaN,NaN,NaN
6,2017-07-22T17:33:38.537426-0500,2167545251640146,55687,dns,180,192.168.198.62,35092,192.168.207.4,53,UDP,query,7425,safebrowsing.clients.google.com.home,A,0.0,NaN,NaN,NaN

In [62]:
# 8. Filtrar los dominios únicos
unique_domains = df_a['dns.rrname'].unique()
print(len(unique_domains))  # Debería ser 177

177

In [63]:
df_a['dns.rrname']

0                               api.wunderground.com
1                                stork79.dropbox.com
2         hpca-tier2.office.aol.com.ad.aol.aoltw.net
5                               api.wunderground.com
6               safebrowsing.clients.google.com.home
                            ...
15713    secure.informaction.com.hsd1.pa.comcast.net
15716                 192.168.22.201:.stayonline.net
15725                             wpad.aol.aoltw.net
15737                       client-software.real.com
15743                       en-us.start3.mozilla.com
Name: dns.rrname, Length: 2849, dtype: object

In [64]:
# 9. Escribir una función que obtenga el TLD para un dominio
def get_tld(domain):
    # Si el dominio termina con '.home', entonces 'home' es el TLD
    if domain.endswith('.home'):
        return 'home'
    # De lo contrario, el TLD es el segundo nivel de dominio y el TLD
    else:
        parts = domain.split('.')
        tld = '.'.join(parts[-2:])
        return tld

In [65]:
# 10. Del dataframe de dominios únicos de tipo A, obtener el TLD
df_a['domain_tld'] = df_a['dns.rrname'].apply(get_tld)
df_a = df_a[['domain_tld']]  # Eliminar todas las demás columnas

In [66]:
df_a

             domain_tld
0      wunderground.com
1           dropbox.com
2             aoltw.net
5      wunderground.com
6                  home
...                 ...
15713       comcast.net
15716    stayonline.net
15725         aoltw.net
15737          real.com
15743       mozilla.com

[2849 rows x 1 columns]

# Parte 2 – Data Science

In [67]:
# Importar el clasificador
from clasificador import clasificacion

In [68]:
# 11. Utilizar el clasificador
df_clasificado = clasificacion(df_a)

In [69]:
df_clasificado.head()

         domain_tld  isDGA
0  wunderground.com      0
1       dropbox.com      1
2         aoltw.net      1
5  wunderground.com      0
6              home      0

In [70]:
# 12. Filtrar aquellos considerados como DGA y mostrarlos
df_dga = df_clasificado[df_clasificado['isDGA'] == 1]
df_dga_unique = df_dga.drop_duplicates()
print(f"Cantidad de registros DGA únicos: {len(df_dga_unique)}")

Cantidad de registros DGA únicos: 36

# Parte 3 – Dominio experto

In [71]:
# Cargar la lista de TLDs
with open('top-1m.csv', 'r') as f:
    tld_list = [line.strip().split(',')[1] for line in f]

# Convertir la lista a un conjunto para búsquedas más rápidas
tld_set = set(tld_list)

def is_in_tld_list(tld):
    return 0 if tld in tld_set else 1

In [72]:
df_dga_unique['not_in_tld_list'] = df_dga_unique['domain_tld'].apply(is_in_tld_list)
df_suspicious = df_dga_unique[df_dga_unique['not_in_tld_list'] == 1]

C:\Users\PARK JONGHYUN\AppData\Local\Temp\ipykernel_38252\4226603419.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dga_unique['not_in_tld_list'] = df_dga_unique['domain_tld'].apply(is_in_tld_list)

In [74]:
!pip install python-whois

Defaulting to user installation because normal site-packages is not writeable
Collecting python-whois
  Downloading python_whois-0.9.3-py3-none-any.whl (103 kB)
Requirement already satisfied: python-dateutil in c:\users\park jonghyun\appdata\roaming\python\python39\site-packages (from python-whois) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\park jonghyun\appdata\roaming\python\python39\site-packages (from python-dateutil->python-whois) (1.16.0)
Installing collected packages: python-whois
Successfully installed python-whois-0.9.3

WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\park jonghyun\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\park jonghyun\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\park jonghyun\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\park jonghyun\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\park jonghyun\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\park jonghyun\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\park jonghyun\appdata\roaming\python\python39\site-packages)

In [75]:
import whois

def get_creation_date(domain):
    try:
        w = whois.whois(domain)
        return w.creation_date
    except Exception as e:
        print(f"Error obteniendo la fecha de creación de {domain}: {e}")
        return None

In [76]:
df_suspicious['creation_date'] = df_suspicious['domain_tld'].apply(get_creation_date)

Error obteniendo la fecha de creación de bigflickrfeed.com: No match for "BIGFLICKRFEED.COM".
>>> Last update of whois database: 2024-04-06T02:54:39Z <<<

NOTICE: The expiration date displayed in this record is the date the
registrar's sponsorship of the domain name registration in the registry is
currently set to expire. This date does not necessarily reflect the expiration
date of the domain name registrant's agreement with the sponsoring
registrar.  Users may consult the sponsoring registrar's Whois database to
view the registrar's reported date of expiration for this registration.

TERMS OF USE: You are not authorized to access or query our Whois
database through the use of electronic processes that are high-volume and
automated except as reasonably necessary to register domain names or
modify existing registrations; the Data in VeriSign Global Registry
Services' ("VeriSign") Whois database is provided by VeriSign for
information purposes only, and to assist persons in obtaining information
about or related to a domain name registration record. VeriSign does not
guarantee its accuracy. By submitting a Whois query, you agree to abide
by the following terms of use: You agree that you may use this Data only
for lawful purposes and that under no circumstances will you use this Data
to: (1) allow, enable, or otherwise support the transmission of mass
unsolicited, commercial advertising or solicitations via e-mail, telephone,
or facsimile; or (2) enable high volume, automated, electronic processes
that apply to VeriSign (or its computer systems). The compilation,
repackaging, dissemination or other use of this Data is expressly
prohibited without the prior written consent of VeriSign. You agree not to
use electronic processes that are automated and high-volume to access or
query the Whois database except as reasonably necessary to register
domain names or modify existing registrations. VeriSign reserves the right
to restrict your access to the Whois database in its sole discretion to ensure
operational stability.  VeriSign may restrict or terminate your access to the
Whois database for failure to abide by these terms of use. VeriSign
reserves the right to modify these terms at any time.

The Registry database contains ONLY .COM, .NET, .EDU domains and
Registrars.

Error obteniendo la fecha de creación de vtlfccmfxlkgifuf.com: No match for "VTLFCCMFXLKGIFUF.COM".
>>> Last update of whois database: 2024-04-06T02:54:39Z <<<

NOTICE: The expiration date displayed in this record is the date the
registrar's sponsorship of the domain name registration in the registry is
currently set to expire. This date does not necessarily reflect the expiration
date of the domain name registrant's agreement with the sponsoring
registrar.  Users may consult the sponsoring registrar's Whois database to
view the registrar's reported date of expiration for this registration.

TERMS OF USE: You are not authorized to access or query our Whois
database through the use of electronic processes that are high-volume and
automated except as reasonably necessary to register domain names or
modify existing registrations; the Data in VeriSign Global Registry
Services' ("VeriSign") Whois database is provided by VeriSign for
information purposes only, and to assist persons in obtaining information
about or related to a domain name registration record. VeriSign does not
guarantee its accuracy. By submitting a Whois query, you agree to abide
by the following terms of use: You agree that you may use this Data only
for lawful purposes and that under no circumstances will you use this Data
to: (1) allow, enable, or otherwise support the transmission of mass
unsolicited, commercial advertising or solicitations via e-mail, telephone,
or facsimile; or (2) enable high volume, automated, electronic processes
that apply to VeriSign (or its computer systems). The compilation,
repackaging, dissemination or other use of this Data is expressly
prohibited without the prior written consent of VeriSign. You agree not to
use electronic processes that are automated and high-volume to access or
query the Whois database except as reasonably necessary to register
domain names or modify existing registrations. VeriSign reserves the right
to restrict your access to the Whois database in its sole discretion to ensure
operational stability.  VeriSign may restrict or terminate your access to the
Whois database for failure to abide by these terms of use. VeriSign
reserves the right to modify these terms at any time.

The Registry database contains ONLY .COM, .NET, .EDU domains and
Registrars.

C:\Users\PARK JONGHYUN\AppData\Local\Temp\ipykernel_38252\1715805563.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_suspicious['creation_date'] = df_suspicious['domain_tld'].apply(get_creation_date)

In [81]:
df_suspicious

,domain_tld,isDGA,not_in_tld_list,creation_date
2,aoltw.net,1,1,2000-01-10 04:09:19
163,22.110phpmyadmin,1,1,None
293,110phpmyadmin.localdomain,1,1,None
363,ntkrnlpa.info,1,1,2023-06-27 08:18:55
583,sql-ledger.org,1,1,2000-09-08 16:25:09
648,backtrack-linux.org,1,1,2009-04-29 00:26:42
796,hackerlabs.vpn,1,1,None
1024,bigflickrfeed.com,1,1,None
1523,malwarecity.com,1,1,"[2008-02-06 15:42:35, 2008-02-06 00:00:00]"
1930,cakephp.org,1,1,2005-06-13 23:07:32
2123,ecvps.com,1,1,2009-05-21 14:24:02
9856,vtlfccmfxlkgifuf.com,1,1,None
9955,macromates.com,1,1,"[2003-02-05 00:25:14, 2003-02-04 19:25:14]"
10646,ejfodfmfxlkgifuf.xyz,1,1,None

- aoltw.net
- ntkrnlpa.info
- ecvps.com
- vtlfccmfxlkgifuf.com
- ejfodfmfxlkgifuf.xyz